nodeLinker: node-modules

# Sikkerhetstiltak mot supply chain-angrep
enableImmutableInstalls: true
enableScripts: false
enableTelemetry: false
checksumBehavior: throw

npmScopes:
  navikt:
    npmAlwaysAuth: true
    npmAuthToken: '${NPM_AUTH_TOKEN:-}'
    npmRegistryServer: 'https://npm.pkg.github.com'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-engines.cjs
    spec: 'https://raw.githubusercontent.com/devoto13/yarn-plugin-engines/main/bundles/%40yarnpkg/plugin-engines.js'
    checksum: 'sha512-e5e6e2885ab0e6521b70b0af7c6d8ca2c75dcae2403706fc4600a783b339a6530a476dafb9450c9436ca4050eb6bdee9b62e6e2cebfecf1e81dd709a2480dc07'

tsEnableAutoTypes: true

yarnPath: .yarn/releases/yarn-4.12.0.cjs
