apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: spinntektsmelding-frontend
  namespace: '{{{namespace}}}'
  labels:
    team: helsearbeidsgiver
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50M"
spec:
  image: {{ image }}
  port: 3000
  ingresses:
    {{#if ingress}}
      {{#each ingress as |i| }}
        - '{{{i}}}'
      {{/each}}
    {{/if}}
  liveness:
    path: /im-dialog/api/is-alive
    initialDelay: 15
    timeout: 5
    periodSeconds: 10
    failureThreshold: 12
  readiness:
    path: /im-dialog/api/is-ready
    initialDelay: 15
    timeout: 5
    periodSeconds: 10
    failureThreshold: 12
  replicas:
    max: 1
    min: 1
  resources:
    limits:
      # cpu: 300m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  idporten:
    enabled: true
    sidecar:
      enabled: true
  tokenx:
    enabled: true
  accessPolicy:
    outbound:
      external:
        - host: '{{{outbound-external-host}}}'
      rules:
        - application: flexjar-backend
          namespace: flex
        - application: nav-dekoratoren
          namespace: personbruker
        - application: im-api
          namespace: helsearbeidsgiver
        - application: sykepengesoknad-backend
          namespace: flex
  env:
    - name: API_URL
      value: '{{{api-url}}}'
    - name: API_BASEPATH
      value: '{{{api-basepath}}}'
    - name: AMPLITUDE_ENABLED
      value: '{{{amplitude-enabled}}}'
   
