const feiltekster = {
  INGEN_ARBEIDSFORHOLD: 'Mangler arbeidsforhold.',
  INGEN_FRAVAERSPERIODER: 'Mangler fraværsperiode.',
  INGEN_FULL_LONN_I_ARBEIDSGIVERPERIODEN: 'Velg om full lønn betales i arbeidsgiverperioden.',
  INGEN_LONN_I_SYKEFRAVAERET: 'Det er ikke registrert lønn.',
  MANGLER_FRA: 'Vennligst angi fra dato.',
  MANGLER_TIL: 'Vennligst angi til dato.',
  IKKE_BEKREFTET: 'Bruttoinntekt er ikke bekreftet.',
  BRUTTOINNTEKT_MANGLER: 'Vennligst anngi bruttoinntekt.',
  LONN_I_ARBEIDSGIVERPERIODEN_MANGLER:
    'Angi om arbeidsgiver betaler ut full lønn til arbeidstaker i arbeidsgiverperioden.',
  LONN_I_ARBEIDSGIVERPERIODEN_BEGRUNNELSE:
    'Begrunnelse for redusert utbetaling av lønn i arbeidsgiverperioden mangler.',
  LONN_UNDER_SYKEFRAVAERET_MANGLER: 'Angi om arbeidsgiver betaler lønn under hele eller deler av sykefraværet.',
  LONN_UNDER_SYKEFRAVAERET_BELOP:
    'Angi refusjonsbeløpet arbeidsgiver har betalt under hele eller deler av sykefraværet.',
  LONN_UNDER_SYKEFRAVAERET_SLUTTDATO_VELG: 'Angi om arbeidsgiver betaler lønn under hele perioden.',
  LONN_UNDER_SYKEFRAVAERET_SLUTTDATO: 'Angi siste dato det kreves refusjon for.',
  BEKREFT_OPPLYSNINGER: 'Bekreft at opplysningene gitt er riktig og fullstendige.',
  ENDRINGSAARSAK_MANGLER: 'Vennligst anngi årsak for endringen.',
  SUM_LAVERE_ENN_INNTEKT: 'Summen av inntektene for de enkelte arbeidsforholdene er høyere enn bruttoinntekten.',
  SERVERFEIL_ARBEIDSGIVER: 'Kunne ikke hente ut arbeidsgiverdata.',
  SERVERFEIL_IM: 'Kunne ikke hente ut inntektsmeldingdata.',
  SERVERFEIL_INNTEKT: 'Kunne ikke hente ut inntektsdata.',
  BRUTTOINNTEKT_ARBEIDSFORHOLD_MANGLER: 'Angi bruttoinntekt for minst et arbeidsforhold.',
  FOR_MANGE_DAGER_MELLOM: 'Det kan ikke være mer enn 16 dager mellom periodene.',
  FOR_MANGE_DAGER_I_PERIODE: 'Det kan ikke være mer enn 16 dager i perioden.',
  MANGLER_TYPE: 'Angi naturalytelse.',
  MANGLER_BORTFALLSDATO: 'Angi dato naturalytelsen bortfaller.',
  MANGLER_VERDI: 'Angi verdien på naturalytelsen.',
  LONN_I_ARBEIDSGIVERPERIODEN_BELOP: 'Angi beløp. Må være over 0.',
  MANGLER_VALG_ENDRING_MAANEDSLONN_I_PERIODEN: 'Angi om det har vært endring i månedslønn i perioden',
  MANGLER_BELOP: 'Angi ny lønn',
  MANGLER_DATO: 'Angi dato for lønnsendring',
  FERIE_FOM: 'Angi fra dato',
  FERIE_TOM: 'Angi til dato',
  LONNSENDRING_FOM_MANGLER: 'Angi fra dato',
  LONNSENDRING_FOM_ETTER_BFD: 'Lønnsendring må ha skjedd før sykefrværet startet',
  TARIFFENDRING_FOM: 'Angi dato for tariffendring',
  TARIFFENDRING_KJENT: 'Angi dato tariffendring ble kjent',
  PERMISJON_FOM: 'Angi fra dato',
  PERMISJON_TOM: 'Angi til dato',
  PERMISJON_MANGLER: 'Angi tid for permisjon',
  NYSTILLING_FOM_MANGLER: 'Angi fra dato',
  NYSTILLING_FOM_ETTER_BFD: 'Endring av stilling må ha skjedd før sykefrværet startet',
  NYSTILLINGSPROSENT_FOM_ETTER_BFD: 'Endring av stillingsprosent må ha skjedd før sykefrværet startet',
  NYSTILLINGSPROSENT_FOM_MANGLER: 'Angi fra dato',
  TIL_FOR_FRA: 'Til dato er før fra dato'
};

export default feiltekster;
