import { z } from 'zod/v4';

export const NaturalytelseEnumSchema = z.enum(
  [
    'AKSJERGRUNNFONDSBEVISTILUNDERKURS',
    'ANNET',
    'BEDRIFTSBARNEHAGEPLASS',
    'BESOEKSREISERHJEMMETANNET',
    'BIL',
    'BOLIG',
    'ELEKTRONISKKOMMUNIKASJON',
    'FRITRANSPORT',
    'INNBETALINGTILUTENLANDSKPENSJONSORDNING',
    'KOSTBESPARELSEIHJEMMET',
    'KOSTDAGER',
    'KOSTDOEGN',
    'LOSJI',
    'OPSJONER',
    'RENTEFORDELLAAN',
    'SKATTEPLIKTIGDELFORSIKRINGER',
    'TILSKUDDBARNEHAGEPLASS',
    'YRKEBILTJENESTLIGBEHOVKILOMETER',
    'YRKEBILTJENESTLIGBEHOVLISTEPRIS'
  ],
  {
    error: (issue) => ({ error: 'Vennligst velg ytelse.' })
  }
);
